/**
 * generate-env.js
 * ─────────────────────────────────────────────────────────────
 * Runs BEFORE `ng build` on Netlify (see netlify.toml).
 * Reads Netlify environment variables and writes the real
 * environment.ts so Angular can import it at build time.
 *
 * Required Netlify env vars (set in Site → Environment Variables):
 *   PORTFOLIO_EMAIL        your email address
 *   PORTFOLIO_LINKEDIN_URL your LinkedIn profile URL
 *   PORTFOLIO_GITHUB_URL   your GitHub profile URL
 */

const fs   = require('fs');
const path = require('path');

const email       = process.env.PORTFOLIO_EMAIL        || '';
const linkedinUrl = process.env.PORTFOLIO_LINKEDIN_URL || '';
const githubUrl   = process.env.PORTFOLIO_GITHUB_URL   || '';

if (!email || !linkedinUrl || !githubUrl) {
  console.warn(
    '[generate-env] WARNING: One or more environment variables are missing.\n' +
    '  PORTFOLIO_EMAIL, PORTFOLIO_LINKEDIN_URL, PORTFOLIO_GITHUB_URL\n' +
    '  The build will continue but links may be empty.'
  );
}

const content = `// AUTO-GENERATED by scripts/generate-env.js — do not edit manually.
export const environment = {
  email:       '${email}',
  linkedinUrl: '${linkedinUrl}',
  githubUrl:   '${githubUrl}',
};
`;

const outDir  = path.join(__dirname, '..', 'src', 'environments');
const outFile = path.join(outDir, 'environment.ts');

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outFile, content, 'utf8');

console.log('[generate-env] environment.ts written successfully.');
